#include "game.h"

using namespace std;

Game::Game()
{

}

static Position START_POSITION = {
    { PIECE_WHITE_ROOK, PIECE_WHITE_KNIGHT, PIECE_WHITE_BISHOP, PIECE_WHITE_QUEEN, PIECE_WHITE_KING, PIECE_WHITE_BISHOP, PIECE_WHITE_KNIGHT, PIECE_WHITE_ROOK },
    { PIECE_WHITE_PAWN, PIECE_WHITE_PAWN, PIECE_WHITE_PAWN, PIECE_WHITE_PAWN, PIECE_WHITE_PAWN, PIECE_WHITE_PAWN, PIECE_WHITE_PAWN, PIECE_WHITE_PAWN },
    { EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE },
    { EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE },
    { EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE },
    { EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE, EMPTY_SQUARE },
    { PIECE_BLACK_PAWN, PIECE_BLACK_PAWN, PIECE_BLACK_PAWN, PIECE_BLACK_PAWN, PIECE_BLACK_PAWN, PIECE_BLACK_PAWN, PIECE_BLACK_PAWN, PIECE_BLACK_PAWN },
    { PIECE_BLACK_ROOK, PIECE_BLACK_KNIGHT, PIECE_BLACK_BISHOP, PIECE_BLACK_QUEEN, PIECE_BLACK_KING, PIECE_BLACK_BISHOP, PIECE_BLACK_KNIGHT, PIECE_BLACK_ROOK }
};


void Game::newGame()
{
    this->setPosition(START_POSITION);
}

void Game::setPosition(Position pos)
{
    for (int y = 0; y < NUM_COLS; y++)
    {
        for (int x = 0; x < NUM_ROWS; x++)
        {
            this->position[x][y] = pos[x][y];
        }
    }
}
