#ifndef GAME_PIECES_H
#define GAME_PIECES_H

#define PIECE_EMPTY_SQUARE -1
#define PIECE_UNDEFINED -10

#define PIECE_WHITE_PAWN 1
#define PIECE_WHITE_KNIGHT 2
#define PIECE_WHITE_BISHOP 3
#define PIECE_WHITE_ROOK 4
#define PIECE_WHITE_QUEEN 5
#define PIECE_WHITE_KING 6

#define PIECE_BLACK_PAWN 11
#define PIECE_BLACK_KNIGHT 12
#define PIECE_BLACK_BISHOP 13
#define PIECE_BLACK_ROOK 14
#define PIECE_BLACK_QUEEN 15
#define PIECE_BLACK_KING 16

#endif // GAME_PIECES_H
